"""External ECG foundation-representation evaluation contracts."""

from ecg_trust.foundation.adapter import (
    FoundationEncoderAdapter,
    FoundationEncoderProtocol,
    PrivateEmbeddingArtifact,
    float32_tensor_sha256,
    model_state_sha256,
    verify_trainable_parameters,
)
from ecg_trust.foundation.comparison import (
    ComparisonCohortMember,
    ComparisonRole,
    FoundationComparisonPlan,
    IndependenceAssessment,
    assert_comparison_role_isolation,
    validate_foundation_comparison_plan,
)
from ecg_trust.foundation.contracts import (
    CANONICAL_DTYPE,
    CANONICAL_INPUT_SAMPLES,
    CANONICAL_INPUT_UNIT,
    CANONICAL_SAMPLING_FREQUENCY_HZ,
    EXTERNAL_ONLY_LIMIT,
    RESEARCH_USE_LIMIT,
    EvaluationMode,
    FoundationAdapterError,
    FoundationError,
    FoundationIntegrityError,
    FoundationModelSpec,
    KnownOverlapDisclosure,
    OverlapStatus,
    PretrainingDatasetDisclosure,
    TrainabilityError,
    TrainabilityPolicy,
)

__all__ = [
    "CANONICAL_DTYPE",
    "CANONICAL_INPUT_SAMPLES",
    "CANONICAL_INPUT_UNIT",
    "CANONICAL_SAMPLING_FREQUENCY_HZ",
    "EXTERNAL_ONLY_LIMIT",
    "RESEARCH_USE_LIMIT",
    "ComparisonCohortMember",
    "ComparisonRole",
    "EvaluationMode",
    "FoundationAdapterError",
    "FoundationComparisonPlan",
    "FoundationEncoderAdapter",
    "FoundationEncoderProtocol",
    "FoundationError",
    "FoundationIntegrityError",
    "FoundationModelSpec",
    "IndependenceAssessment",
    "KnownOverlapDisclosure",
    "OverlapStatus",
    "PretrainingDatasetDisclosure",
    "PrivateEmbeddingArtifact",
    "TrainabilityError",
    "TrainabilityPolicy",
    "assert_comparison_role_isolation",
    "float32_tensor_sha256",
    "model_state_sha256",
    "validate_foundation_comparison_plan",
    "verify_trainable_parameters",
]
