"""Retrospective longitudinal ECG research contracts and aggregate evaluation."""

from ecg_trust.longitudinal.contracts import (
    AGGREGATE_ONLY_LIMIT,
    NON_CAUSAL_TARGET_LIMIT,
    RESEARCH_USE_LIMIT,
    BinaryFutureTarget,
    CensoringPolicy,
    ECGEncounter,
    FollowUpStatus,
    FutureEventDefinition,
    LongitudinalError,
    LongitudinalIntegrityError,
    RoleIsolationError,
    SourceRole,
    TargetStatus,
    TemporalLeakageError,
    TimelineConfig,
)
from ecg_trust.longitudinal.evaluation import (
    CalibrationBin,
    CalibrationBinStatus,
    EvaluationStatus,
    MetricEstimate,
    MetricStatus,
    RiskEvaluationConfig,
    RiskObservation,
    TimeDependentRiskEvaluation,
    evaluate_time_dependent_binary_risk,
)
from ecg_trust.longitudinal.splits import (
    TemporalPartition,
    TemporalSplitAssignment,
    TemporalSplitManifest,
    build_temporal_split_manifest,
)
from ecg_trust.longitudinal.timeline import (
    LongitudinalCohort,
    LongitudinalCohortSummary,
    PatientFutureTargets,
    PatientTimeline,
    assert_no_temporal_leakage,
    assert_patient_source_role_isolation,
    build_patient_timelines,
    derive_future_event_targets,
)

__all__ = [
    "AGGREGATE_ONLY_LIMIT",
    "NON_CAUSAL_TARGET_LIMIT",
    "RESEARCH_USE_LIMIT",
    "BinaryFutureTarget",
    "CalibrationBin",
    "CalibrationBinStatus",
    "CensoringPolicy",
    "ECGEncounter",
    "EvaluationStatus",
    "FollowUpStatus",
    "FutureEventDefinition",
    "LongitudinalCohort",
    "LongitudinalCohortSummary",
    "LongitudinalError",
    "LongitudinalIntegrityError",
    "MetricEstimate",
    "MetricStatus",
    "PatientFutureTargets",
    "PatientTimeline",
    "RiskEvaluationConfig",
    "RiskObservation",
    "RoleIsolationError",
    "SourceRole",
    "TargetStatus",
    "TemporalLeakageError",
    "TemporalPartition",
    "TemporalSplitAssignment",
    "TemporalSplitManifest",
    "TimeDependentRiskEvaluation",
    "TimelineConfig",
    "assert_no_temporal_leakage",
    "assert_patient_source_role_isolation",
    "build_patient_timelines",
    "build_temporal_split_manifest",
    "derive_future_event_targets",
    "evaluate_time_dependent_binary_risk",
]
