"""Preregistered, aggregate-only human-factors research contracts."""

from ecg_trust.human_factors.study import (
    AGGREGATE_ONLY_LIMIT,
    NON_CLINICAL_LIMIT,
    RESEARCH_USE_LIMIT,
    USABILITY_CLAIM_LIMIT,
    ArmAggregate,
    CaseSource,
    EvidenceStatus,
    HumanFactorsError,
    PairedAggregate,
    ParticipantAction,
    ParticipantSchedule,
    StudyArm,
    StudyCase,
    StudyDataError,
    StudyIntegrityError,
    StudyPreregistration,
    StudyResponse,
    StudySummary,
    StudyThresholds,
    TrialAssignment,
    UsabilityClaimStatus,
    evaluate_study,
    expected_action,
    randomize_participant_schedule,
    verify_participant_schedule,
)

__all__ = [
    "AGGREGATE_ONLY_LIMIT",
    "NON_CLINICAL_LIMIT",
    "RESEARCH_USE_LIMIT",
    "USABILITY_CLAIM_LIMIT",
    "ArmAggregate",
    "CaseSource",
    "EvidenceStatus",
    "HumanFactorsError",
    "PairedAggregate",
    "ParticipantAction",
    "ParticipantSchedule",
    "StudyArm",
    "StudyCase",
    "StudyDataError",
    "StudyIntegrityError",
    "StudyPreregistration",
    "StudyResponse",
    "StudySummary",
    "StudyThresholds",
    "TrialAssignment",
    "UsabilityClaimStatus",
    "evaluate_study",
    "expected_action",
    "randomize_participant_schedule",
    "verify_participant_schedule",
]
