"""Content-addressed release registry primitives."""

from ecg_trust.registry.release import (
    MAX_MANIFEST_BYTES,
    TRUST_BUNDLE_BODY_SCHEMA_VERSION,
    TRUST_BUNDLE_COMPATIBILITY_SCHEMA_VERSION,
    TRUST_BUNDLE_PARENT_SCHEMA_VERSION,
    TRUST_BUNDLE_SCHEMA_VERSION,
    ArtifactRole,
    ReleaseRegistryError,
    TrustBundle,
    TrustBundleBody,
    TrustBundleCompatibility,
    TrustBundleCompatibilityError,
    TrustBundleFormatError,
    TrustBundleIntegrityError,
    TrustBundleParent,
    VerifiedTrustBundle,
    bind_parent_file,
    canonical_json_bytes,
    canonical_sha256,
    load_and_verify_trust_bundle,
    load_trust_bundle_manifest,
    save_trust_bundle_manifest,
    seal_trust_bundle,
    sha256_file,
    verify_trust_bundle,
)

__all__ = [
    "MAX_MANIFEST_BYTES",
    "TRUST_BUNDLE_BODY_SCHEMA_VERSION",
    "TRUST_BUNDLE_COMPATIBILITY_SCHEMA_VERSION",
    "TRUST_BUNDLE_PARENT_SCHEMA_VERSION",
    "TRUST_BUNDLE_SCHEMA_VERSION",
    "ArtifactRole",
    "ReleaseRegistryError",
    "TrustBundle",
    "TrustBundleBody",
    "TrustBundleCompatibility",
    "TrustBundleCompatibilityError",
    "TrustBundleFormatError",
    "TrustBundleIntegrityError",
    "TrustBundleParent",
    "VerifiedTrustBundle",
    "bind_parent_file",
    "canonical_json_bytes",
    "canonical_sha256",
    "load_and_verify_trust_bundle",
    "load_trust_bundle_manifest",
    "save_trust_bundle_manifest",
    "seal_trust_bundle",
    "sha256_file",
    "verify_trust_bundle",
]
